---
- name: install nginx server
  hosts: all
  become: yes
  vars_files:
  - vars.yaml
  tasks:
  - name: installing nginx server 
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes