---
- name: variables
  hosts: all
  become: yes
  vars_prompt:
   - name: username
     prompt: please enter username
     private: false
   - name: password
     prompt: please enter your password
     private: yes
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, username: {{username}}, password: {{password}}"